### ISSUE TITLE
Stack Options

### ISSUE THREAD

**Issue by zerolfc** [willsteinmetz/notific8#80]
It would be good if you add stack and custom ID options (only one notification at the time).
```
stack: (true or false)
id: user-defined-id
```
or an option to add ID option, so let the user define the ID for the notification.

for example:
```<article class="notific8-notification family-atomic atomic pear sticky has-heading open" id="user-defined-ID"></article>```

**Comment by willsteinmetz** [comment]
Hi @zerolfc,

If I'm reading what you're trying to do with stacking correctly, you probably want the queue option. Somehow I missed that in the docs but I just added it.

I can add an option for a custom ID.

**Comment by willsteinmetz** [comment]
@zerolfc the `id` option was added in version 4.4.0.

**Comment by zerolfc** [comment]
@willsteinmetz thank you for the effort :)
